### ISSUE TITLE
java.net.UnknownHostException when connecting to db

### ISSUE THREAD

**Issue by maxdarque** [maxdarque/prisma-docker#1]
Then I run `docker-compose up` I get the following error:

```sh
meep:prisma-docker Max$ docker-compose up
Starting prisma ... done
Attaching to prisma
prisma    | Listening for transport dt_socket at address: 8000
prisma    | Exception in thread "main" java.sql.SQLTransientConnectionException: internalRoot - Connection is not available, request timed out after 5001ms.
prisma    | 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
prisma    | 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
prisma    | 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
prisma    | 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
prisma    | 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:18)
prisma    | 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:439)
prisma    | 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:47)
prisma    | 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:38)
prisma    | 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:218)
prisma    | 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:217)
prisma    | 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:38)
prisma    | 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:239)
prisma    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
prisma    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
prisma    | 	at java.lang.Thread.run(Thread.java:748)
prisma    | Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host="my-rds-instances.eu-west-1.rds.amazonaws.com")(port=3306)(type=master) : "my-rds-instances.eu-west-1.rds.amazonaws.com"
prisma    | 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
prisma    | 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
prisma    | 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040)
prisma    | 	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490)
prisma    | 	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:144)
prisma    | 	at org.mariadb.jdbc.Driver.connect(Driver.java:90)
prisma    | 	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
prisma    | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
prisma    | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
prisma    | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
prisma    | 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
prisma    | 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
prisma    | 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
prisma    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
prisma    | 	... 3 more
prisma    | Caused by: java.net.UnknownHostException: "my-rds-instances.eu-west-1.rds.amazonaws.com"
prisma    | 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
prisma    | 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
prisma    | 	at java.net.Socket.connect(Socket.java:589)
prisma    | 	at java.net.Socket.connect(Socket.java:538)
prisma    | 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:398)
prisma    | 	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1032)
prisma    | 	... 14 more
prisma exited with code 1
```

It looks like the db connection is initialized in this file: [Databases.scala](https://github.com/graphcool/prisma/blob/7b3da2706b9c80a4f17bfa2e571c11618d58f735/server/api/src/main/scala/com/prisma/api/database/Databases.scala)

The config is pulled from here [application.conf](https://github.com/graphcool/prisma/blob/7b3da2706b9c80a4f17bfa2e571c11618d58f735/server/api/src/main/resources/application.conf):

```
clientDatabases {
  client1 {
    master {
      connectionInitSql="set names utf8mb4"
      dataSourceClass = "slick.jdbc.DriverDataSource"
      properties {
        url = "jdbc:mysql://"${SQL_CLIENT_HOST}":"${SQL_CLIENT_PORT}"/?autoReconnect=true&useSSL=false&serverTimeZone=UTC&useUnicode=true&characterEncoding=UTF-8&usePipelineAuth=false"
        user = ${SQL_CLIENT_USER}
        password = ${SQL_CLIENT_PASSWORD}
      }
      numThreads = ${SQL_CLIENT_CONNECTION_LIMIT}
      connectionTimeout = 5000
    }
  }
}

schemaManagerEndpoint = ${CLUSTER_ADDRESS}/cluster/schema
schemaManagerSecret = ${SCHEMA_MANAGER_SECRET}
```

**Comment by maxdarque** [comment]
This was happening because I used use double quotes (`"`) in the `.env` file for the DB_HOST. This caused the `java.net.UnknownHostException` error.
