### ISSUE TITLE
Could not generate token for local cluster

### ISSUE THREAD

**Issue by maxdarque** [maxdarque/prisma-docker#3]
When I run `prisma deploy`, I get the following error:

```
Could not generate token for local cluster example-cluster. error:0906D06C:PEM routines:PEM_read_bio:no start line
```

Maybe my keys are not in sync?

**Comment by maxdarque** [comment]
Could be illformed secrets, see here https://github.com/graphcool/prisma/issues/1813

**Comment by maxdarque** [comment]
From https://github.com/graphcool/prisma/issues/1686, I've copied a post

Key copied in `.env` file is not being replaced properly `docker-compose.yml` file. Running docker-compose config shows public key in docker-compose as:

```
CLUSTER_PUBLIC_KEY: '-----BEGIN PUBLIC KEY-----\r\nxxxxxxxxxxxxxxxxxxxxxxxxx\r\nnxxxxxxxxxxxxxxxxxxxxxxxxx\r\nnxxxxxxxxxxxxxxxxxxxxxxxxx\r\nnxxxxxxxxxxxxxxxxxxxxxxxxx\r\nxxxxxxxxxxxxxxxxxxxxxxxxx\r\nnxxxxxxxxxxxxxxxxxxxxxxxxx\r\nxxxxxx\r\n-----END PUBLIC KEY-----'
```
when it should be as

```
 CLUSTER_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----\r\nxxxxxxxxxxxxxxxxxxxxxxxxx\r\
    \nxxxxxxxxxxxxxxxxxxxxxxxxx\r\nxxxxxxxxxxxxxxxxxxxxxxxxx\r\
    \nxxxxxxxxxxxxxxxxxxxxxxxxx\r\nxxxxxxxxxxxxxxxxxxxxxxxxx\r\
    \nxxxxxxxxxxxxxxxxxxxxxxxxx\r\nxxxxxxx\r\
    \n-----END PUBLIC KEY-----"
```

Hard coding key directly in docker-compose file instead of picking it up from .env file works.

**Comment by maxdarque** [comment]
Here's the stack trace:

```
$ /Users/Max/graphql-server/node_modules/.bin/prisma deploy
  config CWD /Users/Max/graphql-server +0ms
  config HOME /Users/Max +2ms
  config definitionDir /Users/Max/graphql-server/database +9ms
  config definitionPath /Users/Max/graphql-server/database/prisma.yml +0ms
  cli { isGlobal: false } +0ms
  StatusChecker setting status checker +0ms
  cli command id deploy +7ms
  cli:plugincache Got plugin from cache +0ms
  cli:plugincache /Users/Max/Library/Caches/prisma/plugins.json +1ms
  cli:plugincache Got plugin from cache +1ms
  cli:plugincache /Users/Max/Library/Caches/prisma/plugins.json +0ms
  plugins findCommand prisma-cli-core +0ms
  plugin requiring command +0ms
  cli-engine:plugins:manager requiring /Users/Max/graphql-server/node_modules/prisma-cli-core +0ms
  portfinder:defaultHosts exports._defaultHosts is: [ '0.0.0.0', '127.0.0.1', '::1', 'fe80::1', 'fe80::ce3:1944:bda8:b43d', '192.168.1.211', 'fdaa:bbcc:ddee:0:c77:51ec:1987:b315', 'fdaa:bbcc:ddee:0:1d6a:71ed:feac:4ae6', '2a00:23c4:8e18:6b00:47f:9ec8:8e93:7cac', '2a00:23c4:8e18:6b00:200d:e0a6:a59e:5097', 'fe80::b845:27ff:feec:7c0d', 'fe80::f6c6:7304:3a9a:dd9b', 'fe80::6a35:3f38:17b4:6168' ] +0ms
  cli-engine:plugins:manager required +3s
  plugin required command +3s
  Environment [ 'prisma-eu1', 'prisma-us1' ] +0ms
  Environment { 'prisma-eu1': 'https://eu1.prisma.sh',
  Environment   'prisma-us1': 'https://us1.prisma.sh' } +1ms
  StatusChecker setting status checker +3s
  deploy run +0ms
Error: Could not generate token for local cluster example-cluster. error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Cluster.getLocalToken (/Users/Max/graphql-server/node_modules/prisma-yml/src/Cluster.ts:81:15)
    at Cluster.<anonymous> (/Users/Max/graphql-server/node_modules/prisma-yml/src/Cluster.ts:53:19)
    at step (/Users/Max/graphql-server/node_modules/prisma-yml/dist/Cluster.js:32:23)
    at Object.next (/Users/Max/graphql-server/node_modules/prisma-yml/dist/Cluster.js:13:53)
    at /Users/Max/graphql-server/node_modules/prisma-yml/dist/Cluster.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/Users/Max/graphql-server/node_modules/prisma-yml/dist/Cluster.js:3:12)
    at Cluster.getToken (/Users/Max/graphql-server/node_modules/prisma-yml/dist/Cluster.js:60:16)
    at Client.<anonymous> (/Users/Max/graphql-server/node_modules/prisma-cli-engine/src/Client/Client.ts:131:33)
    at step (/Users/Max/graphql-server/node_modules/prisma-cli-engine/dist/Client/Client.js:32:23)
    at Object.next (/Users/Max/graphql-server/node_modules/prisma-cli-engine/dist/Client/Client.js:13:53)
    at /Users/Max/graphql-server/node_modules/prisma-cli-engine/dist/Client/Client.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/Users/Max/graphql-server/node_modules/prisma-cli-engine/dist/Client/Client.js:3:12)
    at Client.initClusterClient (/Users/Max/graphql-server/node_modules/prisma-cli-engine/dist/Client/Client.js:55:16)
    at Deploy.<anonymous> (/Users/Max/graphql-server/node_modules/prisma-cli-core/src/commands/deploy/index.ts:175:23)
    at step (/Users/Max/graphql-server/node_modules/prisma-cli-core/dist/commands/deploy/index.js:42:23)
    at Object.next (/Users/Max/graphql-server/node_modules/prisma-cli-core/dist/commands/deploy/index.js:23:53)
    at fulfilled (/Users/Max/graphql-server/node_modules/prisma-cli-core/dist/commands/deploy/index.js:14:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
Exiting with code: 1
```

**Comment by maxdarque** [comment]
Looks like the error is thrown here https://github.com/graphcool/prisma/blob/master/cli/packages/prisma-yml/src/Cluster.ts#L81

```
     const grants = [{ target: `*/*`, action: '*' }]

      try {
        this.cachedToken = jwt.sign({ grants }, this.clusterSecret, {
          expiresIn: '10 minutes',
          algorithm: 'RS256',
        })
      } catch (e) {
        throw new Error(
          `Could not generate token for local cluster ${chalk.bold(
            this.name,
          )}. ${e.message}`,
        )
      }
```

**Comment by maxdarque** [comment]
If I used single quote marks for the key in the `~/.prisma/config.yml`, I would get the original error. So I changed to double quotes (") and it works.
