### ISSUE TITLE
Cluster secret does not match

### ISSUE THREAD

**Issue by maxdarque** [maxdarque/prisma-docker#4]
On `prisma deploy` to my local prisma in docker, I get the following error:

```
Error: Cluster secret of cluster 'example-cluster' saved in ~/.prisma/config.yml
does not match with the actual cluster secret of that cluster. This means the key pair got out of sync.
```

Here is the full stack trace

```
plugin required command +3s
  Environment [ 'prisma-eu1', 'prisma-us1' ] +0ms
  Environment { 'prisma-eu1': 'https://eu1.prisma.sh',
  Environment   'prisma-us1': 'https://us1.prisma.sh' } +1ms
  StatusChecker setting status checker +3s
  deploy run +0ms
  client Token xxxxxxxxxx +0ms
  client Sending query to cluster example-cluster +128ms
  client http://localhost:4466/cluster +0ms
  client 
  client       query($name: String! $stage: String!) {
  client         project(name: $name stage: $stage) {
  client           name
  client           stage
  client         }
  client       }
  client      +0ms
  client { name: 'graphql-server', stage: 'dev' } +0ms

Creating stage dev for service graphql-server...  client Sending query to cluster example-cluster +1s
  client http://localhost:4466/cluster +0ms
  client       mutation addProject($name: String! $stage: String! $secrets: [String!]) {
  client         addProject(input: {
  client           name: $name,
  client           stage: $stage
  client           secrets: $secrets
  client         }) {
  client           project {
  client             name
  client           }
  client         }
  client       }
  client        +1ms
  client { name: 'graphql-server',
  client   stage: 'dev',
  client   secrets: 
  client    [ '-----BEGINRSAPRIVATEKEY-----xxxxxxxxx-----ENDRSAPRIVATEKEY-----' ] } +0ms
 !
Error: Cluster secret of cluster `example-cluster` saved in ~/.prisma/config.yml
does not match with the actual cluster secret of that cluster. This means the key pair got out of sync.
To reset the key pair, please run prisma local start

    at Client.<anonymous> (/Users/Max/graphql-server/node_modules/prisma-cli-engine/src/Client/Client.ts:164:19)
    at step (/Users/Max/graphql-server/node_modules/prisma-cli-engine/dist/Client/Client.js:32:23)
    at Object.throw (/Users/Max/graphql-server/node_modules/prisma-cli-engine/dist/Client/Client.js:13:53)
    at rejected (/Users/Max/graphql-server/node_modules/prisma-cli-engine/dist/Client/Client.js:5:65)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
Exiting with code: 1
```

Here are the logs from my Prisma instance

```
{"key":"error/handled",
"requestId":"cluster:cluster:cje2qyg1y000301646zg8w0mo",
"payload":{
  "exception":"com.prisma.deploy.schema.InvalidToken: Authentication token is invalid: Token can't be decoded: Illegal base64 character 22",
  "query":"      mutation addProject($name: String! $stage: String! $secrets: [String!]) {
        addProject(input: {
          name: $name,
          stage: $stage
          secrets: $secrets
        }) {
          project {
            name
          }
        }
      }",
  "variables":"{
    "name":"graphql-server",
    "stage":"dev",
    "secrets":["-----BEGINRSAPRIVATEKEY-----xxxxxxx-----ENDRSAPRIVATEKEY-----"]
  }",
  "code":"3015",
  "stack_trace":"com.prisma.deploy.server.ClusterAuthImpl.$anonfun$verify$1(ClusterAuth.scala:44)
  scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
  scala.util.Try$.apply(Try.scala:209)
  com.prisma.deploy.server.ClusterAuthImpl.verify(ClusterAuth.scala:28)
  com.prisma.deploy.schema.SchemaBuilderImpl.verifyAuthOrThrow(SchemaBuilder.scala:261)
  com.prisma.deploy.schema.SchemaBuilderImpl.$anonfun$addProjectField$3(SchemaBuilder.scala:213)
  sangria.relay.Mutation$.$anonfun$fieldWithClientMutationId$3(Mutation.scala:41)
  sangria.execution.Resolver.resolveField(Resolver.scala:1024)
  sangria.execution.Resolver.resolveSingleFieldSeq(Resolver.scala:236)
  sangria.execution.Resolver.$anonfun$resolveSeq$2(Resolver.scala:216)
  scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:302)
  scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
  scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
  akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
  akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
  scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
  scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
  akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
  akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
  akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
  akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
  akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
  akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
  akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)",
  "message": "Authentication token is invalid: Token can't be decoded: Illegal base64 character 22"
  }
}
```

**Comment by maxdarque** [comment]
Looks like a configuration issue and how private + public keys are parsed.

I had to hardcode `CLUSTER_PUBLIC_KEY` and `SCHEMA_MANAGER_SECRET` into `docker-compose.yml` for Prisma. I also had to hardcode `secret` in `prisma.yml` on my graphql-server

**Comment by maxdarque** [comment]
need to find a better way to manage keys to keep them out of git

**Comment by maxdarque** [comment]
**From Nilan in the Graphcool forum**
> I believe what you observe is caused by the spaces included in your PRISMA_SECRET. As mentioned in the docs, spaces in the secret are ignored.
> 
> Also, it looks like you are providing your cluster secret from ~/.prisma/config.yml as the value for PRISMA_SECRET. That is not intended. PRISMA_SECRET is the service secret that you can freely define for yourself. Typically, you would use long and random, alphanumeric string like ZpoQeVFGQADqgQRg2J2RT9PE9hXXvxqC.
> 
> Edit: Also note that APP_SECRET is again entirely up to you to define. I strongly recommend to choose different secrets for your application and your Prisma service

**my response:**

> Yes agreed APP_SECRET should be different to PRISMA_SECRET. I was lazy and copied across the RSA private key.
> 
> Looks like I had misunderstood PRISMA_SECRET. I had thought it was related to clusterSecret in ~/.prisma/config.yml which looks to be untrue.
> 
> So your prisma service is secured by PRISMA_SECRET when you deploy and that is used again when you launch your server?

**Nilan**

> The API of a Prisma Service can be protected by one or more secrets. You can change the secrets associated with a Prisma Service by deploying a new list of secrets. The main reason for supporting multiple secrets is to allow removing a secret without service interruptions.
> 
> You can only connect to a Prisma API that is protected by a secret when passing a JWT that has a certain structure and is signed by that secret. The documentation provides more information.
> 
> prisma token and the Prisma constructor from prisma-binding take away the cumbersome work of generating such a valid JWT. So, when you’re initializing your prisma-binding, you need to provide the service secret.

**Comment by maxdarque** [comment]
I think `SCHEMA_MANAGER_SECRET` should be a hex secret like `PRISMA_SECRET` so it can be called from `.env` which is great.

This why at the moment only `CLUSTER_PUBLIC_KEY` is hardcoded into my docker-compose.yml file
